name: Build and deploy Jekyll site to GitHub Pages

on: [push, pull_request]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get -yqq install ruby ruby-all-dev
      - name: Build the site in the jekyll/builder container
        run: |
          export JEKYLL_VERSION=jekyll:latest
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
